service: translation-chain-endpoint
frameworkVersion: "4"

provider:
  name: aws
  runtime: ruby3.3
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
            - "ssm:PutParameter"
          Resource: "arn:aws:ssm:${self:provider.region}:*:parameter/translation-chain/*"

functions:
  translation_chain:
    handler: app.lambda_handler
    events:
      - httpApi:
          path: /translates
          method: get

resources:
  Resources:
    ssmParam:
      Type: "AWS::SSM::Parameter"
      Properties:
        Name: "/translation-chain/deepl-auth-key"
        Type: String
        Value: ${file(./secrets.yml):deeplAuthKey}

